Repository pylhc/omc3, pull requests merged in 2020-09, with the labels that each got.

#211 FIxes #210: aligned longitudinal phase to correct reference turn
  omc3/harpy/frequency.py
  tests/accuracy/test_harpy.py
Labels: bug

#216 Fixes #215: does not search BPM closest to the exciter in model compensation
  omc3/optics_measurements/tune.py
Labels: bug

#214 Fixes #213: Changed the .loc with potentially missing labels
  omc3/optics_measurements/dispersion.py
  omc3/optics_measurements/measure_optics.py
Labels: minor issue

#191 Enhancement/186/crdt
  .travis.yml
  README.md
  omc3/harpy/constants.py
  omc3/harpy/frequency.py
  omc3/harpy/handler.py
  omc3/harpy/kicker.py
  omc3/hole_in_one.py
  omc3/model/accelerators/accelerator.py
  omc3/model/write_macros.py
  omc3/optics_measurements/crdt.py
  omc3/optics_measurements/measure_optics.py
  omc3/optics_measurements/rdt.py
  omc3/scripts/write_madx_macros.py
  omc3/tbt/reader_iota.py
  omc3/utils/stats.py
  tests/accuracy/test_crdt.py
  tests/inputs/crdt/coupling/coupling1.linx
  tests/inputs/crdt/coupling/coupling1.liny
  tests/inputs/crdt/coupling/coupling2.linx
  tests/inputs/crdt/coupling/coupling2.liny
  tests/inputs/crdt/coupling/coupling3.linx
  tests/inputs/crdt/coupling/coupling3.liny
  tests/inputs/crdt/coupling/ptc_crdt.tfs
  tests/inputs/crdt/octupole/octupole1.linx
  tests/inputs/crdt/octupole/octupole1.liny
  tests/inputs/crdt/octupole/octupole2.linx
  tests/inputs/crdt/octupole/octupole2.liny
  tests/inputs/crdt/octupole/octupole3.linx
  tests/inputs/crdt/octupole/octupole3.liny
  tests/inputs/crdt/octupole/ptc_crdt.tfs
  tests/inputs/crdt/sextupole/ptc_crdt.tfs
  tests/inputs/crdt/sextupole/sextupole1.linx
  tests/inputs/crdt/sextupole/sextupole1.liny
  tests/inputs/crdt/sextupole/sextupole2.linx
  tests/inputs/crdt/sextupole/sextupole2.liny
  tests/inputs/crdt/sextupole/sextupole3.linx
  tests/inputs/crdt/sextupole/sextupole3.liny
  tests/inputs/crdt/skewsextupole/ptc_crdt.tfs
  tests/inputs/crdt/skewsextupole/skewsextupole1.linx
  tests/inputs/crdt/skewsextupole/skewsextupole1.liny
  tests/inputs/crdt/skewsextupole/skewsextupole2.linx
  tests/inputs/crdt/skewsextupole/skewsextupole2.liny
  tests/inputs/crdt/skewsextupole/skewsextupole3.linx
  tests/inputs/crdt/skewsextupole/skewsextupole3.liny
  tests/inputs/models/25cm_beam1/modifiers.madx
  tests/inputs/models/inj_beam1/error_deffs.txt
  tests/inputs/models/inj_beam1/opticsfile.1
  tests/inputs/models/inj_beam1/twiss.dat
  tests/unit/test_stats.py
Labels: enhancement
