Repository pylhc/omc3, pull requests merged in 2021-07, with the labels that each got.

#290 Add element dropping option for the tbt_converter
  omc3/tbt/handler.py
  omc3/tbt_converter.py
Labels: enhancement

#291 Pathlib for tbt functionality and tests for --drop_elements
  omc3/tbt/handler.py
  omc3/tbt/reader_esrf.py
  omc3/tbt/reader_iota.py
  omc3/tbt/reader_lhc.py
  omc3/tbt/reader_ptc.py
  omc3/tbt/reader_trackone.py
  omc3/tbt_converter.py
  tests/unit/test_tbt.py
Labels: enhancement

#289 Enhancement/30/coupling
  omc3/optics_measurements/beta_from_phase.py
  omc3/optics_measurements/coupling.py
  omc3/optics_measurements/measure_optics.py
  omc3/optics_measurements/phase.py
  omc3/optics_measurements/rdt.py
  setup.py
  tests/accuracy/test_measure_optics.py
  tests/accuracy/twiss_to_lin.py
Labels: enhancement

#294 No modifiers error message fix
  omc3/model/accelerators/accelerator.py
  omc3/model/accelerators/lhc.py
Labels: bug

#303 Model Creator Fix
  omc3/madx_wrapper.py
  omc3/model/model_creators/abstract_model_creator.py
  omc3/model/model_creators/lhc_model_creator.py
  omc3/model/model_creators/ps_model_creator.py
  omc3/model/model_creators/psbooster_model_creator.py
  omc3/model_creator.py
  omc3/plotting/utils/colors.py
  tests/conftest.py
  tests/unit/test_model_creator.py
Labels: bug

#304 Upload documentation artifacts for PR events
  .github/workflows/documentation.yml
Labels: documentation, enhancement, feature
