Repository pylhc/omc3, pull requests merged in 2022-09, with the labels that each got.

#390 For tbt0.4
  omc3/__init__.py
  omc3/hole_in_one.py
  omc3/tbt_converter.py
  setup.py
  tests/accuracy/test_harpy.py
Labels: Bug

#391 CI Updates
  .github/workflows/coverage.yml
  .github/workflows/cron.yml
  .github/workflows/documentation.yml
  .github/workflows/publish.yml
  .github/workflows/tests.yml
Labels: CI/CD

#392 Initialize dataframe with float instead of int
  omc3/correction/handler.py
Labels: Bugfix

#394 Knob extractor plus
  .github/workflows/coverage.yml
  .github/workflows/cron.yml
  .github/workflows/tests.yml
  CHANGELOG.md
  README.md
  doc/entrypoints/other.rst
  doc/modules/tbt.rst
  omc3/__init__.py
  omc3/knob_extractor.py
  setup.cfg
  setup.py
  tests/inputs/knob_extractor/knob_definitions.txt
  tests/inputs/knob_extractor/knobs_2022-06-25.txt
  tests/unit/test_knob_extractor.py
Labels: Feature

#399 Knob extractor pandafied
  CHANGELOG.md
  omc3/__init__.py
  omc3/knob_extractor.py
  tests/unit/test_knob_extractor.py
Labels: Enhancement
