Repository pylhc/omc3, pull requests merged in 2023-06, with the labels that each got.

#417 Workflows and doc fixes
  .github/workflows/README.md
  .github/workflows/coverage.yml
  .github/workflows/cron.yml
  .github/workflows/documentation.yml
  .github/workflows/publish.yml
  .github/workflows/tests.yml
  doc/entrypoints/analysis.rst
  doc/entrypoints/correction.rst
  doc/entrypoints/other.rst
  doc/entrypoints/plotting.rst
  doc/entrypoints/scripts.rst
  doc/modules/correction.rst
  doc/modules/definitions.rst
  doc/modules/harpy.rst
  doc/modules/kmod.rst
  doc/modules/model.rst
  doc/modules/optics_measurements.rst
  doc/modules/plotting.rst
  doc/modules/tune_analysis.rst
  doc/modules/utils.rst
  setup.py
Labels: Minor Issue, Documentation, Bugfix, CI/CD

#421 Minor bugfixes june 2023
  MANIFEST.in
  doc/_static/css/custom.css
  doc/_templates/layout.html
  doc/conf.py
  omc3/optics_measurements/beta_from_phase.py
  omc3/optics_measurements/phase.py
  omc3/plotting/plot_optics_measurements.py
  omc3/utils/iotools.py
Labels: Minor Issue, Documentation, Maintenance, Bugfix

#422 Missing Plotting Windows Tests
  CHANGELOG.md
  omc3/__init__.py
  omc3/plotting/utils/windows.py
  tests/unit/test_plot_windows.py
Labels: Enhancement, Bugfix
