Repository pylhc/omc3, pull requests merged in 2024-09, with the labels that each got.

#445 madx pattern for doros BPMs
  CHANGELOG.md
  omc3/__init__.py
  omc3/harpy/frequency.py
  omc3/harpy/handler.py
  omc3/model/madx_macros/general.macros.madx
  omc3/optics_measurements/beta_from_phase.py
  omc3/optics_measurements/kick.py
  omc3/optics_measurements/phase.py
  omc3/optics_measurements/rdt.py
  omc3/tune_analysis/bbq_tools.py
  pyproject.toml
  tests/unit/test_model_creator.py
  tests/unit/test_rdt_magnet_order.py
Labels: Release, Maintenance, Bugfix

#455 Bugfixes: numpy/pandas dtypes, erramp column, path read, special phases
  .gitignore
  CHANGELOG.md
  omc3/__init__.py
  omc3/harpy/constants.py
  omc3/harpy/handler.py
  omc3/hole_in_one.py
  omc3/optics_measurements/beta_from_amplitude.py
  omc3/optics_measurements/coupling.py
  omc3/optics_measurements/crdt.py
  omc3/optics_measurements/data_models.py
  omc3/optics_measurements/dispersion.py
  omc3/optics_measurements/kick.py
  omc3/optics_measurements/measure_optics.py
  omc3/optics_measurements/phase.py
  omc3/optics_measurements/rdt.py
  omc3/optics_measurements/tune.py
  tests/inputs/lhcb1_tbt_inj_on_off_mom/Beam1@BunchTurn@2024_03_08@17_41_48_045_250turns.sdds
  tests/inputs/lhcb1_tbt_inj_on_off_mom/Beam1@BunchTurn@2024_03_08@17_42_58_701_250turns.sdds
  tests/inputs/lhcb1_tbt_inj_on_off_mom/Beam1@BunchTurn@2024_03_08@17_44_07_494_250turns.sdds
  tests/inputs/lhcb1_tbt_inj_on_off_mom/Beam1@BunchTurn@2024_03_08@17_56_20_055_250turns.sdds
  tests/inputs/lhcb1_tbt_inj_on_off_mom/Beam1@BunchTurn@2024_03_08@17_57_41_540_250turns.sdds
  tests/inputs/lhcb1_tbt_inj_on_off_mom/Beam1@BunchTurn@2024_03_08@17_58_53_905_250turns.sdds
  tests/inputs/lhcb1_tbt_inj_on_off_mom/Beam1@BunchTurn@2024_03_08@18_24_02_100_250turns.sdds
  tests/inputs/lhcb1_tbt_inj_on_off_mom/Beam1@BunchTurn@2024_03_08@18_25_23_729_250turns.sdds
  tests/inputs/lhcb1_tbt_inj_on_off_mom/Beam1@BunchTurn@2024_03_08@18_26_41_811_250turns.sdds
  tests/inputs/lhcb1_tbt_inj_on_off_mom/truncate_turns.py
  tests/unit/test_hole_in_one.py
Labels: Type: Bug, Type: Feature, Priority: High, Status: In Progress, Estimate: Normal

#458 Global Correction Fixes
  CHANGELOG.md
  omc3/__init__.py
  omc3/check_corrections.py
  omc3/correction/filters.py
  omc3/correction/handler.py
  omc3/global_correction.py
  omc3/model/accelerators/lhc.py
  omc3/model/accelerators/lhc/2012/correctors/correctors_b1/beta_correctors.json
  omc3/model/accelerators/lhc/2012/correctors/correctors_b2/beta_correctors.json
  omc3/model/accelerators/lhc/2024/correctors/correctors_b1/beta_correctors.json
  omc3/model/accelerators/lhc/2024/correctors/correctors_b2/beta_correctors.json
  omc3/model/accelerators/lhc/corrector_elems_b1.tfs
  omc3/model/accelerators/lhc/corrector_elems_b2.tfs
  omc3/model/accelerators/lhc/correctors/corrector_elems_b1.tfs
  omc3/model/accelerators/lhc/correctors/corrector_elems_b2.tfs
  omc3/model/accelerators/lhc/correctors/correctors_b1/beta_correctors.json
  omc3/model/accelerators/lhc/correctors/correctors_b1/coupling_correctors.json
  omc3/model/accelerators/lhc/correctors/correctors_b2/beta_correctors.json
  omc3/model/accelerators/lhc/correctors/correctors_b2/coupling_correctors.json
  omc3/model/accelerators/lhc/correctors/coupling_correctors_small.json
  omc3/model/accelerators/lhc/correctors/triplet_correctors.json
  omc3/plotting/plot_checked_corrections.py
  omc3/plotting/utils/windows.py
  tests/conftest.py
  tests/unit/test_check_corrections.py
  tests/unit/test_global_correction.py
  tests/unit/test_global_correction_knobs.py
  tests/unit/test_hole_in_one.py
Labels: Type: Bug, Type: Release, Type: Maintenance, Status: In Progress, Priority: Critical, Estimate: Normal

#460 Fix Various Warnings
  .github/workflows/coverage.yml
  CHANGELOG.md
  doc/index.rst
  omc3/__init__.py
  omc3/correction/response_io.py
  omc3/definitions/formats.py
  omc3/kmod/analysis.py
  omc3/model_creator.py
  omc3/optics_measurements/rdt.py
  omc3/plotting/plot_amplitude_detuning.py
  omc3/plotting/spectrum/waterfall.py
  omc3/plotting/utils/annotations.py
  omc3/response_creator.py
  omc3/run_kmod.py
  omc3/scripts/betabeatsrc_output_converter.py
  omc3/tbt_converter.py
  omc3/utils/outliers.py
  tests/accuracy/twiss_to_lin.py
  tests/unit/test_plot_tfs.py
Labels: Estimate: Easy, Priority: Low, Type: Release, Type: Maintenance, Type: CI/CD, Status: Review Needed
