Repository pylhc/omc3, pull requests merged in 2024-11, with the labels that each got.

#466 Add Calculation of DPP in full response and global correction
  CHANGELOG.md
  omc3/__init__.py
  omc3/correction/constants.py
  omc3/correction/filters.py
  omc3/correction/handler.py
  omc3/correction/response_madx.py
  omc3/correction/response_twiss.py
  omc3/global_correction.py
  omc3/model/accelerators/accelerator.py
  omc3/model/accelerators/lhc.py
  omc3/model/madx_macros/general.macros.madx
  omc3/model/model_creators/abstract_model_creator.py
  omc3/response_creator.py
  tests/accuracy/test_global_correction.py
  tests/inputs/correction/deltap/generate_dat.py
  tests/inputs/correction/deltap/twiss_dpp_-1.0e-04_B1.dat
  tests/inputs/correction/deltap/twiss_dpp_-1.0e-04_B2.dat
  tests/inputs/correction/deltap/twiss_dpp_2.5e-04_B1.dat
  tests/inputs/correction/deltap/twiss_dpp_2.5e-04_B2.dat
  tests/unit/test_global_correction.py
Labels: Type: Feature, Type: Release, Priority: Medium, Domain: Physics, Status: Review Needed, Estimate: Normal

#470 Knob extractor spark props
  CHANGELOG.md
  omc3/__init__.py
  omc3/knob_extractor.py
Labels: Type: Bug, Estimate: Easy, Type: Release, Status: Review Needed, Priority: Critical

#427 add get_bad_bpms
  .zenodo.json
  CHANGELOG.md
  README.md
  doc/entrypoints/scripts.rst
  omc3/__init__.py
  omc3/optics_measurements/iforest.py
  omc3/scripts/bad_bpms_summary.py
  tests/inputs/bad_bpms/LHCB1/Measurements/example/bad_bpms_iforest_x.tfs
  tests/inputs/bad_bpms/LHCB1/Measurements/example/bad_bpms_iforest_y.tfs
  tests/inputs/bad_bpms/LHCB1/Measurements/example/example.sdds.bad_bpms_x
  tests/inputs/bad_bpms/LHCB1/Measurements/example/example.sdds.bad_bpms_y
  tests/unit/test_bad_bpms_summary.py
Labels: Type: Feature, Estimate: Easy, Priority: Low, Type: Documentation, Status: On Hold

#471 Fix K-Mod importer
  CHANGELOG.md
  omc3/__init__.py
  omc3/scripts/kmod_import.py
Labels: Type: Bug, Estimate: Easy, Type: Release, Priority: High, Status: Review Needed

#472 Add bad bpms reasons
  CHANGELOG.md
  omc3/__init__.py
  omc3/optics_measurements/iforest.py
  omc3/scripts/bad_bpms_summary.py
  tests/unit/test_bad_bpms_summary.py
Labels: Type: Feature, Estimate: Easy, Priority: Low, Type: Documentation, Type: Release
