Repository pylhc/omc3, pull requests merged in 2025-03, with the labels that each got.

#487 Fix LHC BestKnowledge Model fetcher
  CHANGELOG.md
  omc3/__init__.py
  omc3/model/accelerators/lhc.py
  omc3/model/model_creators/abstract_model_creator.py
  omc3/model/model_creators/lhc_model_creator.py
  omc3/utils/iotools.py
Labels: Type: Bug, Estimate: Easy, Domain: GUI, Priority: High

#485 Add qt5 binding depencendy
  pyproject.toml
Labels: Estimate: Easy, Type: Maintenance, Priority: Medium

#490 SbS Propagable Refactor
  omc3/definitions/formats.py
  omc3/sbs_propagation.py
  omc3/segment_by_segment/constants.py
  omc3/segment_by_segment/definitions.py
  omc3/segment_by_segment/math.py
  omc3/segment_by_segment/propagables.py
  omc3/segment_by_segment/propagables/__init__.py
  omc3/segment_by_segment/propagables/abstract.py
  omc3/segment_by_segment/propagables/alpha.py
  omc3/segment_by_segment/propagables/beta.py
  omc3/segment_by_segment/propagables/phase.py
  omc3/segment_by_segment/propagables/utils.py
  omc3/segment_by_segment/segments.py
  tests/accuracy/test_sbs.py
Labels: Type: Feature, Type: Maintenance, Priority: High, Status: In Progress, Domain: Physics, Estimate: Normal
